name: unix_crypt
description: A unix crypt of apache for Dart, which supports salt crypt string.
version: 1.0.1
author: YPPPK <820235991@qq.com>
homepage: https://github.com/YPPPK/unix_crypt

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
